global:
  scrape_interval: 1m
  evaluation_interval: 1m

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    
    static_configs:
      - targets: ['localhost:7280']